#!/usr/bin/env bash
#configure web-02 to be identical to web-01
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/new_404.html
sudo sed -i '/server_name _/a error_page 404 /new_404.html; \nlocation = /new_404.html \n{\nroot /var/www/html/;\ninternal; \n}' /etc/nginx/sites-available/default
sudo sed -i '/# First attempt to serve request as file, then/a add_header X-Served-By $HOSTNAME;\n' /etc/nginx/sites-available/default
sudo service nginx restart
