#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get install haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 35.185.118.130:80 check\n\tserver web2 34.73.168.214:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
