#!/usr/bin/env bash
#Displays numbers from 1 to 100
#If number is multiple of 3 print Fizz
#If number is multiple of 5 print Buzz
#If is multiple of both print FizzBuzz
for i in {1..100}; do
    if [ $((i%3)) == 0 ] && [ $((i%5)) == 0 ]; then
	echo "FizzBuzz"
    elif [ $((i%3)) == 0 ]; then
	echo "Fizz"
    elif [ $((i%5)) == 0 ]; then
	echo "Buzz"
    else
	echo "$i"
    fi
done
