#!/usr/bin/env bash
#Display's Holberton School 10 times using a while loop and in the 9th prints Hi
i=0
while [ $i -lt 10 ]
do
echo "Holberton School"
if [ $i == 8 ]; then
    echo "Hi"
fi
let "i+=1"
done
