#!/usr/bin/env bash
# Fix container so Nginx runs witj the user nginx
pkill -9 apache2
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
